name: Qiita Sync Debug

on:
  workflow_dispatch:

jobs:
  qiita_sync_check:
    name: qiita-sync check debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install qiita-sync
        run: |
          python -m pip install -i https://test.pypi.org/simple/ qiita-sync
      - name: Run qiita-sync check debug
        run: |
          qiita_sync check --verbose .
        env: 
          QIITA_ACCESS_TOKEN: ${{ secrets.QIITA_ACCESS_TOKEN }}
